export const FEATURES = [
  {
    key: 'wardrobe',
    title: 'My Wardrobe',
    description: 'Manage your clothing collection',
    icon: 'checkroom',
    color: '#6366f1',
    apiPath: '/api/wardrobe',
    aiFeature: 'wardrobe',
    columns: [
      { key: 'name', label: 'Item Name' },
      { key: 'category', label: 'Category' },
      { key: 'color', label: 'Color' },
      { key: 'brand', label: 'Brand' },
      { key: 'size', label: 'Size' },
      { key: 'season', label: 'Season' },
    ],
    fields: [
      { key: 'name', label: 'Item Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Tops', 'Bottoms', 'Dresses', 'Outerwear', 'Shoes', 'Accessories', 'Basics', 'Swimwear', 'Sleepwear'] },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'size', label: 'Size', type: 'text' },
      { key: 'season', label: 'Season', type: 'select', options: ['All Season', 'Spring/Summer', 'Fall/Winter', 'Spring', 'Summer', 'Fall', 'Winter', 'Spring/Fall'] },
      { key: 'image_url', label: 'Image URL', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'outfits',
    title: 'Outfit Ideas',
    description: 'Create and manage outfit combinations',
    icon: 'style',
    color: '#ec4899',
    apiPath: '/api/outfits',
    aiFeature: 'outfits',
    columns: [
      { key: 'name', label: 'Outfit Name' },
      { key: 'occasion', label: 'Occasion' },
      { key: 'top', label: 'Top' },
      { key: 'bottom', label: 'Bottom' },
      { key: 'shoes', label: 'Shoes' },
      { key: 'rating', label: 'Rating' },
    ],
    fields: [
      { key: 'name', label: 'Outfit Name', type: 'text', required: true },
      { key: 'occasion', label: 'Occasion', type: 'select', options: ['Business', 'Casual', 'Evening', 'Smart Casual', 'Semi-Formal', 'Formal', 'Athletic', 'Resort', 'Professional'] },
      { key: 'top', label: 'Top', type: 'text' },
      { key: 'bottom', label: 'Bottom', type: 'text' },
      { key: 'shoes', label: 'Shoes', type: 'text' },
      { key: 'accessories', label: 'Accessories', type: 'text' },
      { key: 'rating', label: 'Rating (1-5)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'style-profile',
    title: 'Style Profile',
    description: 'Define your personal style preferences',
    icon: 'person',
    color: '#8b5cf6',
    apiPath: '/api/style-profile',
    aiFeature: 'style-profile',
    columns: [
      { key: 'attribute', label: 'Attribute' },
      { key: 'value', label: 'Value' },
      { key: 'category', label: 'Category' },
      { key: 'importance', label: 'Importance' },
    ],
    fields: [
      { key: 'attribute', label: 'Attribute', type: 'text', required: true },
      { key: 'value', label: 'Value', type: 'text' },
      { key: 'category', label: 'Category', type: 'select', options: ['General', 'Colors', 'Physical', 'Budget', 'Materials', 'Patterns', 'Footwear', 'Accessories', 'Work', 'Casual', 'Environment', 'Inspiration', 'Habits'] },
      { key: 'importance', label: 'Importance', type: 'select', options: ['High', 'Medium', 'Low'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'occasions',
    title: 'Occasion Planner',
    description: 'Plan outfits for upcoming events',
    icon: 'event',
    color: '#f59e0b',
    apiPath: '/api/occasions',
    aiFeature: 'occasions',
    columns: [
      { key: 'name', label: 'Event' },
      { key: 'event_date', label: 'Date' },
      { key: 'dress_code', label: 'Dress Code' },
      { key: 'location', label: 'Location' },
      { key: 'budget', label: 'Budget' },
    ],
    fields: [
      { key: 'name', label: 'Event Name', type: 'text', required: true },
      { key: 'event_date', label: 'Date', type: 'date' },
      { key: 'dress_code', label: 'Dress Code', type: 'select', options: ['Casual', 'Smart Casual', 'Business Casual', 'Business Professional', 'Semi-Formal', 'Formal', 'Black Tie', 'Cocktail', 'Resort Casual', 'Creative Chic', 'Athletic', 'Outdoor', 'Festive Cocktail'] },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'outfit_plan', label: 'Outfit Plan', type: 'textarea' },
      { key: 'budget', label: 'Budget ($)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'color-analysis',
    title: 'Color Analysis',
    description: 'Discover your perfect color palette',
    icon: 'palette',
    color: '#ef4444',
    apiPath: '/api/color-analysis',
    aiFeature: 'color-analysis',
    columns: [
      { key: 'color_name', label: 'Color' },
      { key: 'hex_code', label: 'Hex Code' },
      { key: 'season_type', label: 'Season' },
      { key: 'category', label: 'Category' },
      { key: 'complements', label: 'Complements' },
    ],
    fields: [
      { key: 'color_name', label: 'Color Name', type: 'text', required: true },
      { key: 'hex_code', label: 'Hex Code', type: 'text' },
      { key: 'season_type', label: 'Season Type', type: 'select', options: ['Spring', 'Summer', 'Autumn', 'Winter', 'All Season'] },
      { key: 'category', label: 'Category', type: 'select', options: ['Core', 'Accent', 'Neutral'] },
      { key: 'complements', label: 'Complementary Colors', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'trends',
    title: 'Trend Tracker',
    description: 'Stay on top of fashion trends',
    icon: 'trending_up',
    color: '#10b981',
    apiPath: '/api/trends',
    aiFeature: 'trends',
    columns: [
      { key: 'name', label: 'Trend' },
      { key: 'category', label: 'Category' },
      { key: 'season', label: 'Season' },
      { key: 'popularity', label: 'Popularity' },
      { key: 'source', label: 'Source' },
    ],
    fields: [
      { key: 'name', label: 'Trend Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Style Movement', 'Bottoms', 'Color', 'Outerwear', 'Texture', 'Material', 'Accessories', 'Movement', 'Footwear', 'Denim'] },
      { key: 'season', label: 'Season', type: 'text' },
      { key: 'year', label: 'Year', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'popularity', label: 'Popularity', type: 'select', options: ['High', 'Medium', 'Low'] },
      { key: 'source', label: 'Source', type: 'text' },
    ],
  },
  {
    key: 'shopping',
    title: 'Shopping List',
    description: 'Track items you want to buy',
    icon: 'shopping_bag',
    color: '#f97316',
    apiPath: '/api/shopping',
    aiFeature: 'shopping',
    columns: [
      { key: 'item_name', label: 'Item' },
      { key: 'brand', label: 'Brand' },
      { key: 'price', label: 'Price' },
      { key: 'priority', label: 'Priority' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'item_name', label: 'Item Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Tops', 'Bottoms', 'Shoes', 'Accessories', 'Outerwear', 'Bags', 'Swimwear', 'Sleepwear', 'Basics'] },
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'price', label: 'Price ($)', type: 'number' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['High', 'Medium', 'Low'] },
      { key: 'store', label: 'Store', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'purchased', 'wishlist'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'outfit-calendar',
    title: 'Outfit Calendar',
    description: 'Plan your daily outfits',
    icon: 'calendar_month',
    color: '#3b82f6',
    apiPath: '/api/outfit-calendar',
    aiFeature: 'outfit-calendar',
    columns: [
      { key: 'date', label: 'Date' },
      { key: 'occasion', label: 'Occasion' },
      { key: 'outfit_name', label: 'Outfit' },
      { key: 'weather', label: 'Weather' },
    ],
    fields: [
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'occasion', label: 'Occasion', type: 'text' },
      { key: 'outfit_name', label: 'Outfit Name', type: 'text' },
      { key: 'top', label: 'Top', type: 'text' },
      { key: 'bottom', label: 'Bottom', type: 'text' },
      { key: 'shoes', label: 'Shoes', type: 'text' },
      { key: 'weather', label: 'Weather', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'style-boards',
    title: 'Style Boards',
    description: 'Create inspiration mood boards',
    icon: 'dashboard',
    color: '#a855f7',
    apiPath: '/api/style-boards',
    aiFeature: 'style-boards',
    columns: [
      { key: 'name', label: 'Board Name' },
      { key: 'theme', label: 'Theme' },
      { key: 'mood', label: 'Mood' },
      { key: 'colors', label: 'Colors' },
    ],
    fields: [
      { key: 'name', label: 'Board Name', type: 'text', required: true },
      { key: 'theme', label: 'Theme', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'mood', label: 'Mood', type: 'text' },
      { key: 'colors', label: 'Colors', type: 'text' },
      { key: 'inspiration', label: 'Inspiration', type: 'textarea' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'clothing-care',
    title: 'Clothing Care',
    description: 'Care instructions for your garments',
    icon: 'local_laundry_service',
    color: '#14b8a6',
    apiPath: '/api/clothing-care',
    aiFeature: 'clothing-care',
    columns: [
      { key: 'garment_type', label: 'Garment' },
      { key: 'material', label: 'Material' },
      { key: 'wash_method', label: 'Wash' },
      { key: 'dry_method', label: 'Dry' },
      { key: 'iron_temp', label: 'Iron' },
    ],
    fields: [
      { key: 'garment_type', label: 'Garment Type', type: 'text', required: true },
      { key: 'material', label: 'Material', type: 'text' },
      { key: 'wash_method', label: 'Wash Method', type: 'text' },
      { key: 'dry_method', label: 'Dry Method', type: 'text' },
      { key: 'iron_temp', label: 'Iron Temperature', type: 'text' },
      { key: 'storage', label: 'Storage', type: 'text' },
      { key: 'special_notes', label: 'Special Notes', type: 'textarea' },
    ],
  },
  {
    key: 'budget',
    title: 'Fashion Budget',
    description: 'Track your fashion spending',
    icon: 'account_balance_wallet',
    color: '#22c55e',
    apiPath: '/api/budget',
    aiFeature: 'budget',
    columns: [
      { key: 'item_name', label: 'Item' },
      { key: 'category', label: 'Category' },
      { key: 'amount', label: 'Amount' },
      { key: 'purchase_date', label: 'Date' },
      { key: 'store', label: 'Store' },
    ],
    fields: [
      { key: 'item_name', label: 'Item Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Tops', 'Bottoms', 'Shoes', 'Accessories', 'Outerwear', 'Bags', 'Basics'] },
      { key: 'amount', label: 'Amount ($)', type: 'number' },
      { key: 'purchase_date', label: 'Purchase Date', type: 'date' },
      { key: 'store', label: 'Store', type: 'text' },
      { key: 'payment_method', label: 'Payment Method', type: 'select', options: ['Credit Card', 'Debit Card', 'Cash', 'PayPal', 'Other'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'seasonal',
    title: 'Seasonal Wardrobe',
    description: 'Manage seasonal clothing rotation',
    icon: 'ac_unit',
    color: '#06b6d4',
    apiPath: '/api/seasonal',
    aiFeature: 'seasonal',
    columns: [
      { key: 'item_name', label: 'Item' },
      { key: 'category', label: 'Category' },
      { key: 'season', label: 'Season' },
      { key: 'status', label: 'Status' },
      { key: 'condition', label: 'Condition' },
    ],
    fields: [
      { key: 'item_name', label: 'Item Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Tops', 'Bottoms', 'Dresses', 'Outerwear', 'Shoes', 'Accessories', 'Basics', 'Swimwear'] },
      { key: 'season', label: 'Season', type: 'select', options: ['Spring', 'Summer', 'Fall', 'Winter'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'In Storage'] },
      { key: 'storage_location', label: 'Storage Location', type: 'text' },
      { key: 'condition', label: 'Condition', type: 'select', options: ['Excellent', 'Good', 'Fair', 'Poor'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'mix-match',
    title: 'Mix & Match',
    description: 'AI-powered outfit combinations',
    icon: 'shuffle',
    color: '#e11d48',
    apiPath: '/api/mix-match',
    aiFeature: 'mix-match',
    columns: [
      { key: 'name', label: 'Combo Name' },
      { key: 'top', label: 'Top' },
      { key: 'bottom', label: 'Bottom' },
      { key: 'style', label: 'Style' },
      { key: 'rating', label: 'Rating' },
    ],
    fields: [
      { key: 'name', label: 'Combination Name', type: 'text', required: true },
      { key: 'top', label: 'Top', type: 'text' },
      { key: 'bottom', label: 'Bottom', type: 'text' },
      { key: 'shoes', label: 'Shoes', type: 'text' },
      { key: 'accessories', label: 'Accessories', type: 'text' },
      { key: 'style', label: 'Style', type: 'text' },
      { key: 'occasion', label: 'Occasion', type: 'text' },
      { key: 'rating', label: 'Rating (1-5)', type: 'number' },
    ],
  },
  {
    key: 'style-quiz',
    title: 'Style Quiz',
    description: 'Discover your style personality',
    icon: 'quiz',
    color: '#d946ef',
    apiPath: '/api/style-quiz',
    aiFeature: 'style-quiz',
    columns: [
      { key: 'question', label: 'Question' },
      { key: 'answer', label: 'Answer' },
      { key: 'category', label: 'Category' },
      { key: 'result_type', label: 'Result' },
    ],
    fields: [
      { key: 'question', label: 'Question', type: 'text', required: true },
      { key: 'answer', label: 'Your Answer', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'score', label: 'Score', type: 'number' },
      { key: 'result_type', label: 'Result Type', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'fashion-feed',
    title: 'Fashion Feed',
    description: 'Curated style tips and articles',
    icon: 'feed',
    color: '#64748b',
    apiPath: '/api/fashion-feed',
    aiFeature: 'fashion-feed',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'author', label: 'Author' },
      { key: 'source', label: 'Source' },
      { key: 'published_date', label: 'Published' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'published_date', label: 'Published Date', type: 'date' },
    ],
  },
];
